name: Azure-Board2
on:
  push:
    tags:
      - 'release-v*.*'

jobs:
  create-user-story:
    runs-on: nu-laptop  # Use Windows since you have a Windows runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Release Info
        uses: actions/github-script@v6
        id: release
        with:
          script: |
            const release = context.payload.release;
            console.log(`Release: ${release.tag_name}, ${release.name}`);
            core.setOutput("tag_name", release.tag_name);
            core.setOutput("title", release.name);
            core.setOutput("notes", release.body);

      - name: Create Azure DevOps User Story
        shell: powershell
        run: |
          $headers = @{
              "Content-Type" = "application/json"
              "Authorization" = "Bearer ${{ secrets.AZURE_DEVOPS_TOKEN }}"
          }

          $body = @{
              "fields" = @{
                  "System.Title" = "Release: ${{ steps.release.outputs.title }}"
                  "System.Description" = "${{ steps.release.outputs.notes }}"
                  "System.WorkItemType" = "User Story"
              }
          } | ConvertTo-Json -Depth 3

          Invoke-WebRequest -Uri "https://dev.azure.com/test-mh/test/_apis/wit/workitems/User%20Story?api-version=6.0" `
              -Method Post `
              -Headers $headers `
              -Body $body
