name: backend-tag
on:
  push:
    tags:
      - 'dev-release-mediverse-backend-v*.*'

permissions:
  id-token: write
  contents: read
jobs:
  deploy-backend:
    runs-on: ubuntu-latest  # this is a self hosted windows server
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
