# name: frontend
# on:
#   push:
#     branches:
#       - main 
#     paths:
#       - 'frontend/**'
# permissions:
#   id-token: write
#   contents: read
# jobs:
#   deploy-frontend:
#     runs-on: ubuntu-latest  # this is a self hosted windows server
#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Get TIMESTAMP
#       id: get-timestamp
#       run: |
#         echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M')"
