name: Cleanup Folders 
on: 
  schedule: 
    - cron: "21 5 * * *"
# on:
#  schedule:
#     cron: "18 5 * * *"
    
  # workflow_dispatch:
# permissions:
#   id-token: write
#   contents: read

  # cron: "18 5 * * *" # Runs daily at 3:00 AM UTC
jobs:
  cleanup:
    runs-on: nu-laptop
    steps:
    - name: Run Cleanup Script
      run: |
          powershell.exe -ExecutionPolicy Bypass -File "C:\Users/madhukar.hanumantha/Desktop/backup-cleanup.ps1"
