name: Cleanup Folders
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

  # cron: "0 3 * * *" # Runs daily at 3:00 AM UTC
jobs:
  cleanup:
    runs-on: nu-laptop
    steps:
    - name: Run Cleanup Script
      run: |
          powershell.exe -ExecutionPolicy Bypass -File "C:\Users/madhukar.hanumantha/Desktop/backup-cleanup.ps1"
