name: Manual SQL Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: nu-laptop

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy SQL Changes
      run: |
        sqlcmd -S Nulaptop-409 -U test -P test -i ./stored-procedure/*.sql
