name: Dev Deployment

on:
  push:
    tags:
      - 'v*.*'

jobs:
  Dev-Deployment:
    runs-on: nu-laptop
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create text file with tag name
        run: |
          echo "This file was created for tag ${{ github.ref_name }}" > C:\inetpub\wwwroot\Dev\${{ github.ref_name }}.txt
