name: Dev-Deployment

on:
  push:
    tags:
      - 'v*.*'

jobs:
  Dev-Deployment:
    runs-on: nu-laptop
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "This file was created for tag ${{ github.ref_name }}" > C:\inetpub\wwwroot\Dev\${{ github.ref_name }}.txt

      - name: Copy Build Folder to shared drive
        run: |
          mkdir C:\Shared-Drive\${{ github.ref_name }}
          copy C:\inetpub\wwwroot\Dev\${{ github.ref_name }}.txt C:\Shared-Drive\${{ github.ref_name }}\${{ github.ref_name }}.txt
