name: email
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: nu-laptop # this is a self hosted windows server
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy
      run: echo "Deploying application..."

    - name: Assume role and set credentials
      id: assume-role
      run: |
        $RoleCredentials = aws sts assume-role --role-arn "${{ secrets.AWS_IAM_ROLE1 }}" --role-session-name GitHubActionsSession
        $AWS_ACCESS_KEY_ID = $RoleCredentials.Credentials.AccessKeyId
        $AWS_SECRET_ACCESS_KEY = $RoleCredentials.Credentials.SecretAccessKey
        $AWS_SESSION_TOKEN = $RoleCredentials.Credentials.SessionToken
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set aws_session_token $AWS_SESSION_TOKEN
      shell: powershell

    - name: AWS SES Action
      uses: dsfx3d/action-aws-ses@v1
      with:
        to: madhukar.h1988@gmail.com
        from: madhukar.h1988@gmail.com
        subject: GitHub Action Test
        body: This is a test email sent from a GitHub Action.
      env:
        AWS_REGION: us-east-1
    # - name: AWS SES Action
    #   uses: dsfx3d/action-aws-ses@v1
    #   with:
    #     to: madhukar.h1988@gmail.com
    #     from: madhukar.h1988@gmail.com
    #     subject: GitHub Action Test
    #     body: This is a test email sent from a GitHub Action.
    #   env:
    #     role-to-assume: ${{ secrets.AWS_IAM_ROLE1 }}
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #AWS_REGION: us-east-1  # Ensure this is correctly set
      
    # - name: Send Email Notification
    #   if: always()
    #   uses: dawidd6/action-send-mail@v2
    #   with:
    #     server_address: smtp.gmail.com
    #     server_port: 587
    #     username: madjio.tv@gmail.com
    #     password: msru wpku ghal tmjl
    #     subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    #     body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    #     to: madhukar.h1988@gmail.com
    #     from: madhukar.hanumanthappa@nuware.com
