name: email
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: nu-laptop # this is a self hosted windows server
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy
      run: echo "Deploying application..."

    

    - name: Send email using AWS SES
      uses: dsfx3d/action-aws-ses@v1
      with:
        to: madhukar.h1988@gmail.com
        from: madhukar.h1988@gmail.com
        subject: GitHub Action Test
        body: This is a test email sent from a GitHub Action.
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'
      
    # - name: Send Email Notification
    #   if: always()
    #   uses: dawidd6/action-send-mail@v2
    #   with:
    #     server_address: smtp.gmail.com
    #     server_port: 587
    #     username: madjio.tv@gmail.com
    #     password: msru wpku ghal tmjl
    #     subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    #     body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    #     to: madhukar.h1988@gmail.com
    #     from: madhukar.hanumanthappa@nuware.com
