name: email
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: nu-laptop # this is a self hosted windows server
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy1
      run: echo "Deploying application..."

    # - name: Run Deployment Script
    #   id: deploy
    #   run: |
    #     echo "Deploying..."
    #     # Simulate a deployment script
    #     # Replace the following line with your actual deployment command
    #     DEPLOYMENT_STATUS="success"  # Example: change to "failure" if the command fails
        
    #     if [ "$DEPLOYMENT_STATUS" = "success" ]; then
    #       echo "Deployment successful"
    #     else
    #       echo "Deployment failed"
    #     fi

    #     echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
    #     echo "::set-output name=tag::${GITHUB_SHA}"
    #     echo "::set-output name=status::$DEPLOYMENT_STATUS"

    - name: Print Deployment Details
      run: |
        echo "Branch: ${{ steps.deploy.outputs.branch }}"
        echo "Tag: ${{ steps.deploy.outputs.tag }}"
        echo "Status: ${{ steps.deploy.outputs.status }}"

    - name: Send Deployment Email
      uses: dsfx3d/action-aws-ses@v1
      with:
        to: madhukar.hanumanthappa@nuware.com
        from: madhukar.hanumanthappa@nuware.com
        subject: Deployment Notification
        body: |
          Deployment Details:
          - Branch: ${{ steps.deploy.outputs.branch }}
          # - Tag: ${{ steps.deploy.outputs.tag }}
          # - Status: ${{ steps.deploy.outputs.status }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
   
    - name: AWS SES Action
      uses: dsfx3d/action-aws-ses@v1
      with:
        to: madhukar.hanumanthappa@nuware.com
        from: madhukar.hanumanthappa@nuware.com
        subject: GitHub Action Test
        body: This is a test email sent from a GitHub Action.
      env:
        role-to-assume: ${{ secrets.AWS_IAM_ROLE1 }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      
    # - name: Send Email Notification
    #   if: always()
    #   uses: dawidd6/action-send-mail@v2
    #   with:
    #     server_address: smtp.gmail.com
    #     server_port: 587
    #     username: madjio.tv@gmail.com
    #     password: msru wpku ghal tmjl
    #     subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    #     body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    #     to: madhukar.h1988@gmail.com
    #     from: madhukar.hanumanthappa@nuware.com
