name: email
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: nu-laptop # this is a self hosted windows server
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy
      run: echo "Deploying application..."
      
    - name: Send Email Notification
      if: always()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: madjio.tv@gmail.com
        app_password: msru wpku ghal tmjl
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        to: madhukar.h1988@gmail.com
        from: madjio.tv@gmail.com
