name: build-approval-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["deploy-dev"]
    types:
      - completed

jobs:
  deploy-dev:
    runs-on: nu-laptop
    steps:
      - name: Deploy to dev
        run: echo "Deploying to dev environment"

  approve-build:
    runs-on: nu-laptop
    needs: deploy-dev
    steps:
      - name: Waiting for manual approval for build to be marked as successful
        uses: peter-evans/repository-dispatch@v1
        with:
          event-type: build-approval
          repository: pipeline-approvers/CICD-Pipeline
          client-payload: '{"approved": true}'
          token: ${{ secrets.TOKEN }}
      - name: Post-approval step
        if: ${{ github.event.action == 'build-approval' }}
        run: echo "Build approved and deployed successfully!"
