name: build-approval-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["deploy-dev"]
    types:
      - completed

jobs:
  deploy-dev:
    runs-on: nu-laptop
    steps:
      - name: Deploy to dev
        run: echo "Deploying to dev environment"

  approve-build:    
    runs-on: nu-laptop
    environment: UAT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
