name: UAT-Prod

on: 
  workflow_dispatch:
    inputs:
      source-folder:
        description: 'Name of the source folder on C drive'
        required: true
        default: 'source_folder'

jobs:
  Deploy-UAT:
    runs-on: nu-laptop
    environment: UAT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Promote build files to UAT
        run: |
          $sourceFolder = "C:\Shared-Drive\${{ env.SOURCE_FOLDER }}"
          $destinationFolder = "C:\inetpub\wwwroot\UAT"
          New-Item -ItemType Directory -Force -Path $destinationFolder
          Copy-Item -Path "$sourceFolder\\*" -Destination $destinationFolder -Recurse
        shell: powershell
        env:
          SOURCE_FOLDER: ${{ github.event.inputs.source-folder }}

  Deploy-Prod:
    runs-on: nu-laptop
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Promote build files to Prod
        run: |
          $sourceFolder = "C:\Shared-Drive\${{ env.SOURCE_FOLDER }}"
          $destinationFolder = "C:\inetpub\wwwroot\Prod"
          New-Item -ItemType Directory -Force -Path $destinationFolder
          Copy-Item -Path "$sourceFolder\\*" -Destination $destinationFolder -Recurse
        shell: powershell
        env:
          SOURCE_FOLDER: ${{ github.event.inputs.source-folder }}
