name: yes-no

on: 
  workflow_dispatch:
    
jobs:
  Deploy-UAT:
    runs-on: nu-laptop
    environment: UAT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Promote build files to UAT
        run: |
          echo "Deploy uat"

  
          
  Approval-Check:
    runs-on: nu-laptop
    needs: Deploy-UAT
    environment: UAT

    steps:
      - name: Manual approval
        run: |
          if [ "${{ github.event.inputs.approval }}" != "yes" ]; then
            echo "Deployment not approved. Triggering rollback."
            gh workflow run UAT-Prod --ref main --inputs approval=rollback
            exit 1
          else
            echo "Deployment approved."

  Rollback-UAT:
    runs-on: nu-laptop
    needs: Approval-Check
    if: ${{ needs.Approval-Check.outputs.approval == 'rollback' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rollback UAT deployment
        run: |
          echo "rollback uat"
