name: yes-no

on: 
  workflow_dispatch:
    
jobs:
  Deploy-UAT:
    runs-on: nu-laptop
    steps:
      - name: Sanity pass check (manual input)
        id: sanity
        run: |
          echo "Please approve the sanity check by typing 'yes' or 'no'"
          read SANITY_PASS
          echo "SANITY_PASS=$SANITY_PASS" >> $GITHUB_ENV
 
      - name: Fail if sanity check fails
        if: env.SANITY_PASS != 'yes'
        run: |
          echo "Sanity check failed, exiting."
          exit 1
        continue-on-error: false
