name: yes-no
on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: nu-laptop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your deployment steps here
      - name: Deploy application
        run: echo "Deploying application..."

      - name: Manual approval
        run: |
          Write-Host "Awaiting approval (yes/no):"
          $response = Read-Host
          if ($response -ne "yes") {
            Write-Host "Deployment not approved"
            exit 1
          }
        shell: powershell
