name: yes-no

on: 
  workflow_dispatch:
        
jobs:
  Deploy:
    runs-on: nu-laptop
    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Deploy Application
       run: |
         echo "Deploying..."

     - name: Wait for approval
       uses: peter-evans/environment-approval-action@v2
       with:
         environment: UAT  
         
     - name: Rollback if denied
       if: ${{ failure() }}
       run: |
         echo "Deployment was denied. Performing rollback..."

      
       
